# -*- coding: utf-8 -*-
"""read_in_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f_XxnZ7UDKGzgzxDtcGF-eV2fvQFTa9P
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
# %matplotlib inline
from google.colab import drive
drive.mount('/content/drive')

gender = pd.read_csv('/content/drive/MyDrive/gender_data.txt', sep=',')
gender

plt.bar(gender["Fall Term"], gender["Men"])

plt.bar(gender["Fall Term"], gender["Women"])

# n_bins = 10

# men = gender[gender['Men']]
# poultry = gender[gender['Type'] == 'Women']
# meat = gender[gender['Type'] == 'Unknown']


# colors = ['orange', 'blue', 'black']
# labels = ['men','women','unknown']
# x_multi = [men['Calories'], poultry['Calories'], meat['Calories']]
# plt.hist(x_multi, n_bins, histtype='bar',color=colors,label= labels)
# plt.legend(prop={'size': 10})
# plt.xlabel('Year')
# plt.ylabel('Count')

# race = pd.read_csv('/content/drive/My Drive/3. FA22/CS 222/race_data.txt', sep=',')
race = pd.read_csv('/content/drive/MyDrive/race_data.txt', sep=',')

race

race2 = race.drop(['Men', 'Women', 'Unknown', 'All Hawaiian/ Pac Isl'], axis=1)
race2

# # race.drop(columns=['All African American', 'All Native American'])
# race2.rename(columns={"All African American": "drop1", "All Asian": "drop2"})
race2.drop(['All Asian', 'All   African American', 'All    Native American'], axis=1)

racecampustotal = race2.loc[race2['Level'] == "***Campus total***"]
racecampustotal.plot.scatter(x='Fall Term', y = 'Caucasian')

racecampustotal.plot.scatter(x='Fall Term', y = 'Asian American')

racecampustotal.plot.scatter(x='Fall Term', y = 'African American')

racecampustotal.plot.scatter(x='Fall Term', y = 'International')

plt.bar(race2["Fall Term"], race2["Caucasian"])
plt.bar(race2["Fall Term"], race2["Asian American"])
plt.bar(race2["Fall Term"], race2["African American"])
plt.bar(race2["Fall Term"], race2["Hispanic"])
plt.bar(race2["Fall Term"], race2["Native American"])
plt.bar(race2["Fall Term"], race2["Hawaiian/Pacific Isl"])