
# This is a basic workflow to help you get started with Actions

name: Overall Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # jest: 
  #     name: Jest
  #     runs-on: ubuntu-latest

  #     steps: 
  #       - name: Run Jest
  #         # You may pin to the exact commit or the version.
  #         # uses: stefanoeb/jest-action@f9bb23f509cde20ee9b494f0496d1d3323861cc4
  #         uses: stefanoeb/jest-action@1.0.4
  #         with:
  #           # Args to jest
  #           jestArgs: ./client/src/__tests__
  #       - run: npm install

  build:
    name: Jest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
      with:
        jestArgs: ./client/src/__tests__
          
  eslint: 
    name: ESLint
    runs-on: ubuntu-latest
    
    steps: 
      - name: Run ESLint
        # You may pin to the exact commit or the version.
        # uses: stefanoeb/eslint-action@0b532bcd98dbed80a59071fa8986fcf1b1715be4
        uses: stefanoeb/eslint-action@1.0.2
        with:
          # Blob of files to lint
          files: ./client/node_modules/.bin/eslint
